---
driver:
  name: vagrant
  provider: virtualbox

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  playbook: ./nodejs.yml

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    verifier:
      inspec_tests:
        - test/integration/default
suites:
  - name: default
